version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/okura-restful-api
permissions:
  - object: /var/www/html/
    owner: ec2-user
    group: ec2-user
    mode: 777
    pattern: "**"
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/prepair.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
