version: 0.2

phases:
  pre_build:
    commands:
      ## ECRにログイン
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      ## Dockerイメージのタグとして使用するため、Gitのコミットハッシュを取得
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

      ## ECRのURL
      - REPOSITORY_URI=720146896923.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/okura-restful-api
  build:
    commands:
      ## Dockerイメージのビルド
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

      ## DockerイメージのECRへのプッシュ
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"okura-restful-api", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  ## buildの最後で作成したファイルをアーティファクトとして流す
  files:
      - imageDetail.json
cache:
    paths:
        - '/vendor/**/*'

