openapi: "3.0.0"
info:
  description: "商品のデータの登録・検索・変更・削除を行うRESTfulAPIアプリケーション"
  version: "1.0.0"
  title: "RESTfulなAPI"
host: "localhost:8000"
basePath: "/api/v1"
tags:
  - name: "items"
    description: "itemsに関して、登録・編集・削除・検索"
schemes:
  - "http"
paths:
  /items:
    get:
      tags:
        - "items"
      summary: "アイテム全件取得"
      description: "アイテムの全データを取得しjson形式で返す"
      consumes:
        - "application/json"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                properties:
                  Items:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          format: int
                          example: 1
                        name:
                          type: string
                          example: tanaka
                        description:
                          type: string
                          example: スマートフォン
                        price:
                          type: integer
                          format: int
                          example: 10000
                        image:
                          type: string
                          example: http://******
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  count:
                    type: integer
                    format: int
                    example: 100
        '404':
                description: "Not found"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        errors:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 404
                            messages:
                              type: string
                              example: リソースがありませんでした    
    post:
      tags:
       - "items"
      summary: "アイテム登録"
      description: "アイテムを一件登録しjson形式で登録アイテムを返す"
      parameters:
        - in: body
          name: itemBody
          description: itemBody
          required: true
          schema:
            $ref: '#/definitions/Item'
      consumes:
       - "application/json"
      responses:
        '201':
          description: "OK"
          content:
            application/json:
              schema:
                properties:
                  Item:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int
                        example: 1
                      name:
                        type: string
                        example: tanaka
                      description:
                        type: string
                        example: スマートフォン
                      price:
                        type: integer
                        format: int
                        example: 10000
                      image:
                        type: string
                        example: http://******
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                  messages:
                    type: string
                    example: "登録が完了しました。"
        '422':
          description: "バリデーションエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      code:
                        type: int
                        example: 422
                      messages:
                        type: string
                        example: バリデーションエラーです
                      details:
                        type: object 
                        properties:
                          name:
                            type: array
                            items:
                              type: string
                              example: The name field is required.
                          description:
                            type: array
                            items:
                              type: string
                              example: The position field is required.
                          price:
                            type: array
                            items:
                              type: string
                              example: The introduce field is required.
                          image:
                            type: array
                            items:
                              type: string
                              example: The rarity field is required.
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      code:
                        type: int
                        example: 500
                      messages:
                        type: string
                        example: サーバで予期しないエラーが起きました。
  /items/{itemId}:
    put:
      tags:
        - "items"
      summary: "アイテム更新"
      description: "アイテムを一件更新しjson形式で登録アイテムを返す"
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: itemBody
          description: itemBody
          required: true
          schema:
            $ref: '#/definitions/Item'
      consumes:
        - "application/json"
      responses:
          '201':
            description: "OK"
            content:
              application/json:
                schema:
                  properties:
                    Item:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int
                          example: 1
                        name:
                          type: string
                          example: tanaka
                        description:
                          type: string
                          example: スマートフォン
                        price:
                          type: integer
                          format: int
                          example: 10000
                        image:
                          type: string
                          example: http://******
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                    messages:
                      type: string
                      example: "更新が完了しました。"
          '404':
            description: "Not found"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    errors:
                      type: object
                      properties:
                        code:
                          type: int
                          example: 404
                        messages:
                          type: string
                          example: リソースがありませんでした
          '422':
            description: "バリデーションエラー"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    errors:
                      type: object
                      properties:
                        code:
                          type: int
                          example: 422
                        messages:
                          type: string
                          example: バリデーションエラーです
                        details:
                          type: object 
                          properties:
                            name:
                              type: array
                              items:
                                type: string
                                example: The name field is required.
                            description:
                              type: array
                              items:
                                type: string
                                example: The position field is required.
                            price:
                              type: array
                              items:
                                type: string
                                example: The introduce field is required.
                            image:
                              type: array
                              items:
                                type: string
                                example: The rarity field is required.
          '500':  
            description: "Internal Server Error "
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    errors:
                      type: object
                      properties:
                        code:
                          type: int
                          example: 500
                        messages:
                          type: string
                          example: サーバで予期しないエラーが起きました。
    get:
      tags:
        - "items"
      summary: "アイテムID検索"
      description: "アイテムをIDで一件検索しjson形式でアイテムを返す"
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
            format: int64
      consumes:
        - "application/json"
      responses:
          '200':
            description: "OK"
            content:
              application/json:
                schema:
                  properties:
                    Item:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int
                          example: 1
                        name:
                          type: string
                          example: tanaka
                        description:
                          type: string
                          example: スマートフォン
                        price:
                          type: integer
                          format: int
                          example: 10000
                        image:
                          type: string
                          example: http://******
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
          '404':
            description: "Not found"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    errors:
                      type: object
                      properties:
                        code:
                          type: int
                          example: 404
                        messages:
                          type: string
                          example: リソースがありませんでした
          '500':  
            description: "Internal Server Error "
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    errors:
                      type: object
                      properties:
                        code:
                          type: int
                          example: 500
                        messages:
                          type: string
                          example: サーバで予期しないエラーが起きました。 
    delete:
        tags:
          - "items"
        summary: アイテム削除
        description: "アイテムを削除し、json形式でメッセージを返す"
        parameters:
          - name: id
            in: path
            description: id
            required: true
            schema:
              type: integer
              format: int64
        consumes:
          - "application/json"
        responses:
            '204':
              description: "OK"
              content:
                application/json:
                  schema:
                    properties:
                      messages:
                        type: string
                        example: 削除しました
            '404':
                description: "Not found"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        errors:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 404
                            messages:
                              type: string
                              example: リソースがありませんでした
            '500':  
                description: "Internal Server Error "
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        errors:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 500
                            messages:
                              type: string
                              example: サーバで予期しないエラーが起きました。
  /items/search:
    get:
        tags:
          - "items"
        summary: アイテム検索
        description: "アイテムを一件更新しjson形式で登録アイテムを返す"
        parameters:
          - name: keyword
            in: path
            description: 検索ワード
            required: true
            schema:
              type: string
        consumes:
          - "application/json"
        responses:
            '200':
              description: "OK"
              content:
                application/json:
                  schema:
                    properties:
                      items:
                        type: object
                        properties:
                          Item:
                            type: object
                            properties:
                              id:
                                type: integer
                                format: int
                                example: 1
                              name:
                                type: string
                                example: tanaka
                              description:
                                type: string
                                example: スマートフォン
                              price:
                                type: integer
                                format: int
                                example: 10000
                              image:
                                type: string
                                example: http://******
                              created_at:
                                type: string
                                format: date-time
                              updated_at:
                                type: string
                                format: date-time
                      itemCount:
                        type: integer
                        format: int
                        example: 100
            '404':
                description: "Not found"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        errors:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 404
                            messages:
                              type: string
                              example: リソースがありませんでした
            '500':  
                description: "Internal Server Error "
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        errors:
                          type: object
                          properties:
                            code:
                              type: int
                              example: 500
                            messages:
                              type: string
                              example: サーバで予期しないエラーが起きました。
definitions:
  Content:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Item'
        code:
          type: int
          example: 200
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int
        example: 1
      name:
        type: string
        example: tanaka
      description:
        type: string
        example: スマートフォン
      price:
        type: integer
        format: int
        example: 10000
      image:
        type: string
        example: http://******
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    xml:
      name: Item